/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceToVideoRouteImport } from './routes/voice-to-video'
import { Route as TestBillingRouteImport } from './routes/test-billing'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as Agent_studioRouteImport } from './routes/agent_studio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanvasIdRouteImport } from './routes/canvas.$id'

const VoiceToVideoRoute = VoiceToVideoRouteImport.update({
  id: '/voice-to-video',
  path: '/voice-to-video',
  getParentRoute: () => rootRouteImport,
} as any)
const TestBillingRoute = TestBillingRouteImport.update({
  id: '/test-billing',
  path: '/test-billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const Agent_studioRoute = Agent_studioRouteImport.update({
  id: '/agent_studio',
  path: '/agent_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIdRoute = CanvasIdRouteImport.update({
  id: '/canvas/$id',
  path: '/canvas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/supervisor': typeof SupervisorRoute
  '/test-billing': typeof TestBillingRoute
  '/voice-to-video': typeof VoiceToVideoRoute
  '/canvas/$id': typeof CanvasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/supervisor': typeof SupervisorRoute
  '/test-billing': typeof TestBillingRoute
  '/voice-to-video': typeof VoiceToVideoRoute
  '/canvas/$id': typeof CanvasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent_studio': typeof Agent_studioRoute
  '/assets': typeof AssetsRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRoute
  '/supervisor': typeof SupervisorRoute
  '/test-billing': typeof TestBillingRoute
  '/voice-to-video': typeof VoiceToVideoRoute
  '/canvas/$id': typeof CanvasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent_studio'
    | '/assets'
    | '/dashboard'
    | '/knowledge'
    | '/supervisor'
    | '/test-billing'
    | '/voice-to-video'
    | '/canvas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent_studio'
    | '/assets'
    | '/dashboard'
    | '/knowledge'
    | '/supervisor'
    | '/test-billing'
    | '/voice-to-video'
    | '/canvas/$id'
  id:
    | '__root__'
    | '/'
    | '/agent_studio'
    | '/assets'
    | '/dashboard'
    | '/knowledge'
    | '/supervisor'
    | '/test-billing'
    | '/voice-to-video'
    | '/canvas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Agent_studioRoute: typeof Agent_studioRoute
  AssetsRoute: typeof AssetsRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeRoute: typeof KnowledgeRoute
  SupervisorRoute: typeof SupervisorRoute
  TestBillingRoute: typeof TestBillingRoute
  VoiceToVideoRoute: typeof VoiceToVideoRoute
  CanvasIdRoute: typeof CanvasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-to-video': {
      id: '/voice-to-video'
      path: '/voice-to-video'
      fullPath: '/voice-to-video'
      preLoaderRoute: typeof VoiceToVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-billing': {
      id: '/test-billing'
      path: '/test-billing'
      fullPath: '/test-billing'
      preLoaderRoute: typeof TestBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent_studio': {
      id: '/agent_studio'
      path: '/agent_studio'
      fullPath: '/agent_studio'
      preLoaderRoute: typeof Agent_studioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$id': {
      id: '/canvas/$id'
      path: '/canvas/$id'
      fullPath: '/canvas/$id'
      preLoaderRoute: typeof CanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Agent_studioRoute: Agent_studioRoute,
  AssetsRoute: AssetsRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeRoute: KnowledgeRoute,
  SupervisorRoute: SupervisorRoute,
  TestBillingRoute: TestBillingRoute,
  VoiceToVideoRoute: VoiceToVideoRoute,
  CanvasIdRoute: CanvasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
